### ISSUE TITLE
Image fails to load after downloading

### ISSUE THREAD

**Issue by frankcash** [AlexEKoren/Technify#3]
After I download the image (right click -> save as) it fails to open, what gives?

**Comment by frankcash** [comment]
the only thing I see on my local version when this happens

`127.0.0.1 - - [16/Feb/2016 17:24:50] "GET /technify HTTP/1.1" 405 -`

**Comment by frankcash** [comment]
No errors thrown when trying to download via chrome

**Comment by AlexEKoren** [comment]
That's weird.. I'm not sure. Could be a browser issue? Because the image is showing, no?

**Comment by frankcash** [comment]
Yeah, I created this before trying another browser. I'll close this!
